# title: Just the Docs Template
# description: A starter template for a Jeykll site using the Just the Docs theme!
title: "Try and Test"
description: "学习笔记，使用指导文档，等"
theme: just-the-docs
    
# url: https://just-the-docs.github.io
url: https://gdvzz.github.io
    
# aux_links:
# Template Repository: https://github.com/just-the-docs/just-the-docs-template

footer_content: 'Copyright &copy; 2017-2026 Patrick Marsceill and Just the Docs contributors. Distributed by an <a href="https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt">MIT license.</a> <a href="https://www.netlify.com/">This site is powered by Netlify.</a>'